---
title: "Types of Research"
---

## Categories of Research

Research can be fundamental/basic, applied, and action research depending on their nature.

1.  **Fundamental or basic research:** This type of research involves experimental and theoretical work aimed at gaining new knowledge without any immediate practical applications, focusing solely on advancing understanding.

2.  **Applied research:** This research aims to address practical problems, with the goal of improving products or processes, rather than simply gaining knowledge for its own sake.

3.  **Action research:** This methodology combines action and research to explore specific questions, issues, or phenomena through observation, reflection, and intentional interventions, with a focus on immediate application in a local context. This is more participatory than applied research.

4.  **Behavioral research:** Behavioral research is a scientific field that investigates the actions and interactions of individuals and groups. It seeks to understand, describe, and predict behavior through systematic observation, experimentation, and analysis.

## Other Research Types

-   **Historical research:** This type of research aims to describe past events to uncover generalizations that aid in understanding both the past and present and, to some extent, predicting the future.

-   **Descriptive research:** This research focuses on describing the current state of affairs to identify relationships between variables that are not manipulated.

-   **Experimental research:** This research investigates what will happen when specific variables are carefully controlled or manipulated to determine relationships between these manipulated variables and other variables.
