project:
  type: book

book:
  title: "A Comprehensive Research Methodology Guide"
  subtitle: "From Theory to Practice"
  author: "Professor Dr. Md. Kamrul Hasan"
  date: "2024"
  chapters:
    - index.qmd
    - 01-introduction.qmd
    - 02-research-types.qmd
    - 03-research-problem.qmd
    - 04-research-proposal.qmd
    - 05-research-design.qmd
    - 06-experimental-design.qmd
    - 07-measurement-scales.qmd
    - 08-sampling.qmd
    - 09-data-collection.qmd
    - 10-reliability-validity.qmd
    - 11-data-analysis.qmd
    - 12-hypothesis-testing.qmd
    - 13-report-writing.qmd
    - 14-plagiarism-ai.qmd
    - references.qmd

format:
  html:
    theme: cosmo
    css: ../../styles.css
    toc: true
    toc-depth: 3
    number-sections: true
    number-depth: 3
    fig-align: center
    code-tools: true
    code-overflow: wrap
    code-link: true
    highlight-style: pygments
    html-math-method: mathjax
    self-contained: true

website:
  twitter-card: true
  open-graph: true
  description: "A comprehensive guide to research methodology covering all aspects from problem identification to report writing"
  image: images/research-methodology-cover.png

execute:
  echo: false
  warning: false
  message: false