---
title: "Research Methodology"
author: "Prof. Dr. Md. Kamrul Hasan"
date: "2025-04-01"

categories:
  - Training
  - Research Methodology
  - DAE, MoA

format: 
  revealjs:
    smaller: false
    scrollable: true
    incremental: false
    code-block-height: 650px
    logo: ../images/pstu-logo.png
    footer: |
      <a href="https://ruenresearch.com" target="_blank">Resources</a>
    transition: fade
    slide-number: c/t
    multiplex: false
    embed-resources: false
    chalkboard: true
    theme: simple
    css: ../styles.css
    toc: true
    toc-depth: 1
    toc-title: Course Contents

bibliography: references.bib
csl: apa.csl
---

# Research and Knowledge

- Knowledge is the stored information in our brain, books or internet that can be recalled when needed.
- Source of knowledge can be anything and anywhere.
- Knowdge generated using systematic (scientific) process is called science.
- Expression of science is technology. e.g. idea, practice, device, sofware, etc. 


# Research types

- Fundamental research: to generate new knowledge (theory) or test existing theory.
- Experimental research (fundamental): A reserch to investigate the cause-effect relationship between variables.
- Applied research: to solve a specific problem using existing (indigenous/scientific) knowledge.
- Action research: applied research with a focus on immediate application in a local context.
- Behavioral research: to understand human/social behavior. e.g. perception, attitude, motivation, adoption, participation, training effectiveness, adaptation to climate change, etc.


# Research terminologies

- Reserch methodology: ~ How to conduct research?
- Research method: ~ A specific way to collect and analyze data.
- Research design: ~ A plan to conduct research. e.g. qualitative, quantitative, mixed method, experimental design, etc.
- Experiment: ~ A trial or setup involving treatments/interventions and experimental units.
- Experimental design: ~ A plan to apply treatments/interventions in an experiment. e.g. CRD, RCBD, Factorial, pretest-posttest control group design, timeseries design, etc.


# Steps in Research

1. Problem identification
2. Setting research objectives
3. Specififying research methodology
4. Data collection and analysis
5. Intrepretation and conclusion

> Every step includes: Literature review

> Ends the step with: Scientific report writing (presentation/publication)


# Data to Law {.smaller1}

- **Data: **Raw and unprocessed information (numbers, text, images, etc.). e.g. 20, 30, 40, etc.
- **Information:** Processed data with meaning. e.g. 20°C is the average temperature in April.
- **Fact: **Verifiable information. e.g. Water boils at 100°C.
- Evidence: Information that supports or refutes a claim. e.g. observed increase in crop growth with row planing.
- **Hypothesis:** A testable scientific guess about the relationship between variables. e.g. row planing enhances crop growth.
- **Theory:** Proven hypothesis. e.g. balannce fertilizer is better than imbalanced fertilizer for crop growth.
- **Law:** Proven theory with universal applicability. e.g. Law's of learning: readyness, exercise, effect, etc.


# Problem identification

- Problem: A gap between what is and what should be.
- Problem is the guiding force of research. This ensures research quality and resource allocation.
- **Sources of problem:** literature review, and personal experience, observation, discussion with stakeholders, etc. also linked to the exsisting literature.

> Problem must be consistent with the existing knowledge.

> Problem must have newness (innovativeness/novelty).

# Resarech title and objectives {.smaller1}

- Title: 10 - 15 words that reflect the research problem and objectives. Sometimes, it may include methodological aspects.
- Examples: "Effect of row planing on growth and yield of wheat in Bangladesh", "Effect of training on income generation: A socio-psychological analysis using Kirkpatrick's model".
- Titles should avoid dead words (investigate, study, effect, etc.), colon (as in the avove example) and abbreviations.
  
- Objectives: Specific statements that describe what the research aims to achieve. 
- Example: To estimate the effect of training on the adoption of row planing among wheat farmers in Barishal region by the end of 2025.

# Research design: CRD, RCBD, LSD, Factorial



