---
title: "World Food Day 2025"
subtitle: "Hand in Hand for a Better Food and a Better Future"
author: "Prof. Dr. Md. Kamrul Hasan"
institute: "Webinar on Youth Collaboration for a Better Food Future in Bangladesh organizede by World Food Forum (WFF) Bangladesh Chapter Team"
date: "2025-10-16"

categories:
  - World Food Day 2025
  - Food security
  - Plenty-share paradox
  - Webinar

format: 
  revealjs:
    smaller: false
    scrollable: true
    incremental: false
    code-block-height: 650px
    logo: ../images/pstu-logo.png
    footer: |
      <a href="https://ruenresearch.com" target="_blank">Resources</a>
    transition: fade
    slide-number: c/t
    multiplex: false
    embed-resources: false
    chalkboard: true
    theme: simple
    css: ../styles.css
    toc: true
    toc-depth: 1
    toc-title: Course Contents

bibliography: references.bib
csl: apa.csl
---

```{r setup, include=FALSE}
# Render and view presentation
if (interactive()) {
  quarto::quarto_preview()
}
```

## Introduction

- Do you know how many people are dying of hunger right now?
- Between 7,700 and over 20,000 people die every day from hunger-related causes.
- That is roughly 10 every minute (Oxfam, 2024).
- Hunger-related death toll is higher than the combined figure of AIDS, malaria and typhoid.

---

## Plenty-Share Paradox

- The world produces enough food to feed everyone, yet millions still starve.
- Global food output meets 2.5 times the caloric needs, but unfair distribution, conflict, and waste lead to ongoing hunger.

---

## Bangladesh Reality

- Bangladesh produces enough rice for its needs, but it struggles with malnutrition and food insecurity.
- Approximately 17% of the population is food-insecure, particularly in coastal regions.
- Among them around 10% are severely food insecure.
- Climate stress and market inequalities make the situation worse.

---

## Major Causes of Hunger

- Inequitable distribution of food, unequal access to markets and resources (Benassai‑Dalmau et al., 2025).
- Food loss and waste: 21 million tonnes lost annually in Bangladesh (CPD, 2024).
- Global loss 1.3 billion tons than could feed 3 billion people. Globally food insecure people about 2.3 billion.
- Climate and conflict impacts, extreme weather, price volatility, and displacement (Oxfam, 2024).

---

## Rethinking Solutions

Food security = Production × Access × Equity × Sustainability.

**Solutions:**

- Social safety nets and nutrition-sensitive agriculture.
- Local food systems and short value chains.
- Investment in post-harvest management and youth involvement.

---

## Collaboration for Equity

- **National:** fair markets, subsidies, inclusive land policies.
- **Local:** link cooperatives, women’s groups, and markets.
- **Multi-sector:** coordination of universities, NGOs, and government agencies for resilient systems.

---

## Youth as Change Agents

- Youth networks connects innovation and local needs.
- Promote agri-digital tools, climate-smart practices, entrepreneurship.
- Showcase local startups and youth-led agrifood initiatives.

---

## Vision for a Resilient Future

“Food security will not come from producing more, but from sharing better.”

**Action Steps:**

- National database of food insecure households.
- Integrate equity in food policy.
- Build partnerships among people, NGOs and GOs.
- Empower youth and communities.
- Strengthen living labs and science-policy interface 

---

## Conclusion

> “If you cannot feed a hundred people, then feed just one.” — Mother Teresa

- Collective humanity defines our food future.
- Awareness and action for collective humanity.

---

## Further Reading {.smaller6}

::: hanging-indent

Benassai‑Dalmau, R., Voukelatou, V., Schifanella, R., Fiandrino, S., Paolotti, D., & Kalimeri, K. (2025). Unequal journeys to food markets: Continental‑scale evidence from open data in Africa. arXiv preprint arXiv:2505.07913.  
https://arxiv.org/abs/2505.07913

Centre for Policy Dialogue. (2024, February 12). Post-harvest losses eat up 21m tonnes of food a year: CPD. The Daily Star.  
https://www.thedailystar.net/business/news/post-harvest-losses-eat-21m-tonnes-food-year-cpd-3998016

Costlow, L., Herforth, A., Sulser, T. B., Cenacchi, N., & Masters, W. A. (2024). Global analysis reveals persistent shortfalls and regional differences in availability of foods needed for health. arXiv preprint arXiv:2401.01080.  
https://arxiv.org/abs/2401.01080

Oxfam. (2024). Food wars: Conflict, hunger, and globalization 2023–2024.  
https://www.oxfam.org/en/press-releases/21000-people-are-dying-each-day-conflict-fuelled-hunger-around-world

Usman, M. A., & Callo‑Concha, D. (2021). Does market access improve dietary diversity and food security? Evidence from Southwestern Ethiopian smallholder coffee producers. Agricultural and Food Economics, 9(1), 1–19.  
https://agrifoodecon.springeropen.com/articles/10.1186/s40100-021-00190-8

World Bank. (2024, July). Bangladesh wastes 34% of food annually: World Bank study. The Business Standard.  
https://www.tbsnews.net/bangladesh/bangladesh-wastes-34-food-annually-experts-1249056

:::